### ISSUE TITLE
Underline on links in tags looks odd

### ISSUE THREAD

**Issue by peterbe** [potch/hax#1]
<img width="415" alt="screenshot 2015-09-01 10 18 23" src="https://cloud.githubusercontent.com/assets/26739/9611134/d9c8703c-5092-11e5-8756-b54ed2eb5ed0.png">

Might look better with just white on the grey/black background.

**Comment by potch** [comment]
The category "pills" look janky in general. Keeping this bug open to address this.

**Comment by potch** [comment]
got rid of the "pill" shapes. Just a list now.
