### ISSUE TITLE
Manage Subscriptions page looks busted

### ISSUE THREAD

**Issue by callahad** [potch/hax#12]
Check out https://hacks.mozilla.org/comment-subscriptions/

![screen shot 2015-10-06 at 15 01 47](https://cloud.githubusercontent.com/assets/24193/10320861/31da6d5c-6c3b-11e5-95e0-c8515a731611.png)

This is accessed through the link at the bottom of each post by the checkbox that says: "Notify me of followup comments via e-mail. You can also **subscribe** without commenting."

**Comment by potch** [comment]
sure does. How did I miss that? grumble.

**Comment by potch** [comment]
for the life of me I can't find where this comes from.

**Comment by potch** [comment]
Found the "virtual page" in a plugin. Will investigate how to clean it up.

**Comment by potch** [comment]
Found it! Should look better now.
