### ISSUE TITLE
Spacing of social media buttons in the header

### ISSUE THREAD

**Issue by ghost** [potch/hax#18]
Really just a minor tweak: the social media buttons in the header (YouTube, Twitter, RSS) are not properly placed in... (please don't hit me) _Google Chrome_. Works just fine in Firefox. :blush: 

![screenshot-hax](https://cloud.githubusercontent.com/assets/7034813/10383042/73d39a80-6e2a-11e5-9ec1-56f591c58e2c.png)

**Comment by potch** [comment]
Ooh, yes, this should be fixed with a release today.
