### ISSUE TITLE
Nested replies tag everyone as 'author'

### ISSUE THREAD

**Issue by callahad** [potch/hax#35]
Screenshot from https://hacks.mozilla.org/2016/04/you-might-not-need-a-css-framework/#comment-19783, Brandon Zell should not be tagged as author in the third comment.

---

<img width="659" alt="screen shot 2016-04-21 at 18 13 38" src="https://cloud.githubusercontent.com/assets/24193/14727045/cb8527d8-07ec-11e6-93a1-e8bb069124ad.png">

---

**Comment by potch** [comment]
Oh hey, this is fixed!
