### ISSUE TITLE
p is resized on desktop like there is a sidebar

### ISSUE THREAD

**Issue by Mte90** [potch/hax#47]
![immagine](https://user-images.githubusercontent.com/403283/38090502-15c3b5c8-3363-11e8-9122-1f4d8f5c6d18.png)

Removing that css rule (min-width:640px) now the width is the same of the container:
```
.post p, .post ul, .post ol, .discussion, .promo { {
    max-width: 65ch;
}
```

and in that way is showed

![immagine](https://user-images.githubusercontent.com/403283/38090675-99979068-3363-11e8-8225-0b13c983b8da.png)

I am thinking to do a userstyle for stylish until the fix is not available

**Comment by Mte90** [comment]
Uploaded https://userstyles.org/styles/157746/mozilla-hacks-full-width

**Comment by potch** [comment]
Capping the width of paragraphs is intentionally done for readability reasons, so I'm probably not going to remove that rule. Glad it's easy to override for people who prefer things wider though!

**Comment by Mte90** [comment]
The feeling that looking on the page something is missing. I was wondering if there was a sidebar and started inspecting because maybe uBlock was removing something.
Instead the container is more big like the header but the content is more tiny. 
In that way the page became very long only because the article is more tiny than the container.
SO for readability is better something that is on less lines also because there is the effect that the article are very long only because all the space of the today screens is not used.

**Comment by Mte90** [comment]
![38090502-15c3b5c8-3363-11e8-9122-1f4d8f5c6d18](https://user-images.githubusercontent.com/403283/38113263-bcd3748e-33a4-11e8-973f-1c24ca7cb5c9.png)

To explain better the issue

**Comment by digitarald** [comment]
(pardon the drive-by comment) Most sites converged to a centered main element these days (Medium as reading example; but also other layouts like github, facebook, twitter, etc). Maybe this decision can be reconsidered now as it might solve the problem of "looking cut off".

**Comment by Mte90** [comment]
Now github is more organized and doesn't have a sidebar useless like before.
